version: "3.9"
services:
  snmptrapd:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 162:162/udp
    volumes:
      - ./etc/snmp.conf:/etc/snmp/snmp.conf
      - ./etc/snmptrapd.conf:/etc/snmp/snmptrapd.conf
      - ./mibs:/mibs
